-- ============================================================
-- NUFFY — schema
-- Run in Supabase SQL editor (or via migrations).
-- 001: schema + functions
-- ============================================================

-- ---------- lookups ----------

create table if not exists public.rarities (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  color text not null default '#A8AFBB',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.levels (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  sort_order integer not null default 0,
  color text not null default '#A8AFBB',
  multiplier numeric(6,3) not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- ---------- profiles ----------

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  account_id bigint generated by default as identity (start with 520500),
  username text not null unique,
  balance numeric(14,2) not null default 0 check (balance >= 0),
  role text not null default 'user' check (role in ('user','admin')),
  avatar_url text,
  is_banned boolean not null default false,
  banned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), 'user_' || left(new.id::text, 8))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------- catalog ----------

create table if not exists public.collections (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  image_url text,
  total_minted integer not null default 0 check (total_minted >= 0),
  sold_count integer not null default 0 check (sold_count >= 0 and sold_count <= total_minted),
  released_at timestamptz,
  status text not null default 'active'
    check (status in ('draft','pending','active','sold_out','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chips (
  id uuid primary key default gen_random_uuid(),
  collection_id uuid not null references public.collections (id) on delete restrict,
  name text not null,
  image_url text,
  image_crop jsonb not null default '{"x":0.5,"y":0.5,"zoom":1}'::jsonb,
  rarity_id uuid not null references public.rarities (id),
  level_id uuid not null references public.levels (id),
  base_price numeric(14,2) not null check (base_price >= 0),
  number integer not null check (number >= 1),
  total_minted integer not null default 0 check (total_minted >= 0),
  sold_count integer not null default 0 check (sold_count >= 0 and sold_count <= total_minted),
  sold_out boolean generated always as (sold_count >= total_minted) stored,
  status text not null default 'active' check (status in ('draft','active','disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (collection_id, number)
);

create index if not exists chips_collection_idx on public.chips (collection_id);

-- ---------- instances (owned items) ----------

create table if not exists public.chip_instances (
  id uuid primary key default gen_random_uuid(),
  chip_id uuid not null references public.chips (id) on delete restrict,
  serial integer not null check (serial >= 1),
  owner_id uuid references public.profiles (id) on delete set null,
  status text not null default 'owned'
    check (status in ('owned','listed','traded','upgraded','removed','sold')),
  acquired_at timestamptz not null default now(),
  acquired_via text not null default 'shop'
    check (acquired_via in ('shop','pack','trade','upgrade','admin','marketplace')),
  locked_until timestamptz,
  unique (chip_id, serial)
);

create index if not exists chip_instances_owner_idx on public.chip_instances (owner_id);
create index if not exists chip_instances_chip_idx on public.chip_instances (chip_id);

-- ownership / lifecycle history
create table if not exists public.instance_events (
  id bigint generated always as identity primary key,
  instance_id uuid not null references public.chip_instances (id) on delete cascade,
  event text not null,
  actor_user_id uuid,
  from_user_id uuid,
  to_user_id uuid,
  meta jsonb,
  created_at timestamptz not null default now()
);

create index if not exists instance_events_instance_idx on public.instance_events (instance_id);
create index if not exists instance_events_to_user_idx on public.instance_events (to_user_id);

-- ---------- marketplace ----------

create table if not exists public.marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  instance_id uuid not null unique references public.chip_instances (id) on delete restrict,
  seller_id uuid not null references public.profiles (id) on delete cascade,
  price numeric(14,2) not null check (price > 0),
  status text not null default 'listed' check (status in ('listed','sold','cancelled')),
  listed_at timestamptz not null default now(),
  sold_at timestamptz,
  cancelled_at timestamptz
);

create index if not exists marketplace_listings_status_idx on public.marketplace_listings (status);
create index if not exists marketplace_listings_seller_idx on public.marketplace_listings (seller_id);

create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  instance_id uuid not null references public.chip_instances (id) on delete restrict,
  listing_id uuid references public.marketplace_listings (id) on delete set null,
  chip_id uuid not null references public.chips (id),
  buyer_id uuid not null references public.profiles (id),
  seller_id uuid references public.profiles (id),
  amount numeric(14,2) not null,
  fee numeric(14,2) not null default 0,
  type text not null check (type in ('shop','marketplace')),
  created_at timestamptz not null default now()
);

create index if not exists purchases_chip_idx on public.purchases (chip_id);
create index if not exists purchases_buyer_idx on public.purchases (buyer_id);
create index if not exists purchases_listing_idx on public.purchases (listing_id);

-- ---------- favs ----------

create table if not exists public.favorites (
  user_id uuid not null references public.profiles (id) on delete cascade,
  chip_id uuid not null references public.chips (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, chip_id)
);

-- ---------- packs ----------

create table if not exists public.packs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  image_url text,
  price numeric(14,2) not null check (price >= 0),
  status text not null default 'draft' check (status in ('draft','active','paused','ended')),
  available_count integer check (available_count is null or available_count >= 0),
  opened_count integer not null default 0 check (opened_count >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  current_version integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pack_versions (
  id uuid primary key default gen_random_uuid(),
  pack_id uuid not null references public.packs (id) on delete cascade,
  version integer not null,
  config jsonb not null,
  created_at timestamptz not null default now(),
  unique (pack_id, version)
);

-- pack_items: chips inside a version, grouped by tier (index in config.tiers)
create table if not exists public.pack_items (
  id uuid primary key default gen_random_uuid(),
  pack_version_id uuid not null references public.pack_versions (id) on delete cascade,
  tier_id integer not null,
  chip_id uuid not null references public.chips (id),
  weight numeric(12,4) not null check (weight > 0),
  unique (pack_version_id, tier_id, chip_id)
);

create index if not exists pack_items_version_idx on public.pack_items (pack_version_id);

-- ---------- trades ----------

create table if not exists public.trades (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  initiator_id uuid not null references public.profiles (id),
  partner_id uuid references public.profiles (id),
  status text not null default 'pending' check (status in ('pending','completed','cancelled')),
  wants jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '7 days')
);

create index if not exists trades_initiator_idx on public.trades (initiator_id);

create table if not exists public.trade_items (
  id uuid primary key default gen_random_uuid(),
  trade_id uuid not null references public.trades (id) on delete cascade,
  instance_id uuid not null unique references public.chip_instances (id) on delete restrict,
  giver_id uuid not null references public.profiles (id),
  created_at timestamptz not null default now()
);

-- ---------- upgrades ----------

create table if not exists public.upgrades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id),
  source_instance_id uuid not null references public.chip_instances (id),
  target_chip_id uuid not null references public.chips (id),
  balance_spent numeric(14,2) not null default 0 check (balance_spent >= 0),
  chance numeric(5,2) not null check (chance >= 0 and chance <= 100),
  created_at timestamptz not null default now()
);

create table if not exists public.upgrade_attempts (
  id uuid primary key default gen_random_uuid(),
  upgrade_id uuid not null references public.upgrades (id) on delete cascade,
  success boolean not null,
  result_instance_id uuid references public.chip_instances (id),
  rolled_at timestamptz not null default now()
);

create index if not exists upgrades_user_idx on public.upgrades (user_id);

-- ---------- money ----------

create table if not exists public.balance_transactions (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.profiles (id),
  type text not null check (type in
    ('deposit','withdraw','purchase','sale','pack','upgrade','promo',
     'admin_grant','admin_remove','refund','trade','marketplace_buy')),
  amount numeric(14,2) not null,
  balance_before numeric(14,2) not null,
  balance_after numeric(14,2) not null,
  status text not null default 'completed' check (status in ('pending','completed','rejected','cancelled')),
  reference_type text,
  reference_id text,
  description text,
  admin_id uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists balance_transactions_user_idx on public.balance_transactions (user_id);

-- ---------- promo ----------

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  bonus_type text not null check (bonus_type in ('percent','fixed')),
  bonus_value numeric(14,2) not null check (bonus_value > 0),
  max_uses integer not null default 0 check (max_uses >= 0),
  per_user_limit integer not null default 1 check (per_user_limit >= 1),
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default true,
  used_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promo_code_uses (
  id uuid primary key default gen_random_uuid(),
  promo_code_id uuid not null references public.promo_codes (id) on delete cascade,
  user_id uuid not null references public.profiles (id),
  amount numeric(14,2) not null,
  balance_transaction_id bigint references public.balance_transactions (id),
  created_at timestamptz not null default now()
);

create index if not exists promo_uses_user_idx on public.promo_code_uses (user_id);

-- ---------- audit ----------

create table if not exists public.admin_audit_logs (
  id bigint generated always as identity primary key,
  admin_id uuid not null references public.profiles (id),
  action text not null,
  entity text not null,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  ip text,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_idx on public.admin_audit_logs (created_at desc);

-- ---------- triggers ----------

create or replace function public.touch_updated_at()
returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated on public.profiles;
create trigger profiles_updated before update on public.profiles
  for each row execute procedure public.touch_updated_at();

drop trigger if exists collections_updated on public.collections;
create trigger collections_updated before update on public.collections
  for each row execute procedure public.touch_updated_at();

drop trigger if exists chips_updated on public.chips;
create trigger chips_updated before update on public.chips
  for each row execute procedure public.touch_updated_at();

drop trigger if exists packs_updated on public.packs;
create trigger packs_updated before update on public.packs
  for each row execute procedure public.touch_updated_at();

drop trigger if exists promo_codes_updated on public.promo_codes;
create trigger promo_codes_updated before update on public.promo_codes
  for each row execute procedure public.touch_updated_at();

-- ---------- convenience view: inventory ----------

create or replace view public.inventory
with (security_invoker = on) as
select
  ci.id,
  ci.chip_id,
  ci.serial,
  ci.owner_id,
  ci.status,
  ci.acquired_at,
  ci.acquired_via,
  ci.locked_until,
  c.name as chip_name,
  c.number as chip_number,
  c.image_url,
  c.image_crop,
  c.base_price,
  c.collection_id,
  col.name as collection_name,
  col.slug as collection_slug,
  col.total_minted as collection_total,
  col.sold_count as collection_sold,
  col.status as collection_status,
  r.slug as rarity_slug,
  r.name as rarity_name,
  r.color as rarity_color,
  r.sort_order as rarity_order,
  l.name as level_name,
  l.slug as level_slug,
  l.sort_order as level_order
from public.chip_instances ci
join public.chips c on c.id = ci.chip_id
join public.collections col on col.id = c.collection_id
join public.rarities r on r.id = c.rarity_id
join public.levels l on l.id = c.level_id;