-- ============================================================
-- NUFFY — ПОЛНАЯ УСТАНОВКА БАЗЫ ДАННЫХ (один файл вместо 001–004)
--
-- Внутри по порядку:
--   ЧАСТЬ 1 — схема           (эквивалент 001_schema.sql)
--   ЧАСТЬ 2 — бизнес-функции  (эквивалент 002_functions.sql)
--   ЧАСТЬ 3 — RLS и Storage   (эквивалент 003_rls.sql)
--   ЧАСТЬ 4 — демо-данные     (эквивалент 004_seed.sql, с защитой от повтора)
--
-- КАК ЗАПУСКАТЬ:
--   1. Supabase Dashboard → SQL Editor → New query
--   2. Вставьте ВЕСЬ этот файл → Run
-- Больше ничего делать НЕ нужно: не запускайте 001–004 отдельно,
-- они находятся внутри этого файла.
--
-- ПОВТОРНЫЙ ЗАПУСК БЕЗОПАСЕН:
--   Таблицы (IF NOT EXISTS), функции (CREATE OR REPLACE), политики
--   (DROP + CREATE), Storage (ON CONFLICT DO NOTHING).
--   Демо-данные применяются строго один раз (маркер в seed_state).
-- ============================================================


-- ============================================================
-- ЧАСТЬ 1: СХЕМА (001_schema.sql)
-- ============================================================

-- ---------- lookups ----------

create table if not exists public.rarities (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  color text not null default '#A8AFBB',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.levels (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  sort_order integer not null default 0,
  color text not null default '#A8AFBB',
  multiplier numeric(6,3) not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- ---------- profiles ----------

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  account_id bigint generated by default as identity (start with 520500),
  username text not null unique,
  balance numeric(14,2) not null default 0 check (balance >= 0),
  role text not null default 'user' check (role in ('user','admin')),
  avatar_url text,
  is_banned boolean not null default false,
  banned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), 'user_' || left(new.id::text, 8))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------- catalog ----------

create table if not exists public.collections (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  image_url text,
  total_minted integer not null default 0 check (total_minted >= 0),
  sold_count integer not null default 0 check (sold_count >= 0 and sold_count <= total_minted),
  released_at timestamptz,
  status text not null default 'active'
    check (status in ('draft','pending','active','sold_out','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chips (
  id uuid primary key default gen_random_uuid(),
  collection_id uuid not null references public.collections (id) on delete restrict,
  name text not null,
  image_url text,
  image_crop jsonb not null default '{"x":0.5,"y":0.5,"zoom":1}'::jsonb,
  rarity_id uuid not null references public.rarities (id),
  level_id uuid not null references public.levels (id),
  base_price numeric(14,2) not null check (base_price >= 0),
  number integer not null check (number >= 1),
  total_minted integer not null default 0 check (total_minted >= 0),
  sold_count integer not null default 0 check (sold_count >= 0 and sold_count <= total_minted),
  sold_out boolean generated always as (sold_count >= total_minted) stored,
  status text not null default 'active' check (status in ('draft','active','disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (collection_id, number)
);

create index if not exists chips_collection_idx on public.chips (collection_id);

-- ---------- instances (owned items) ----------

create table if not exists public.chip_instances (
  id uuid primary key default gen_random_uuid(),
  chip_id uuid not null references public.chips (id) on delete restrict,
  serial integer not null check (serial >= 1),
  owner_id uuid references public.profiles (id) on delete set null,
  status text not null default 'owned'
    check (status in ('owned','listed','traded','upgraded','removed','sold')),
  acquired_at timestamptz not null default now(),
  acquired_via text not null default 'shop'
    check (acquired_via in ('shop','pack','trade','upgrade','admin','marketplace')),
  locked_until timestamptz,
  unique (chip_id, serial)
);

create index if not exists chip_instances_owner_idx on public.chip_instances (owner_id);
create index if not exists chip_instances_chip_idx on public.chip_instances (chip_id);

-- ownership / lifecycle history
create table if not exists public.instance_events (
  id bigint generated always as identity primary key,
  instance_id uuid not null references public.chip_instances (id) on delete cascade,
  event text not null,
  actor_user_id uuid,
  from_user_id uuid,
  to_user_id uuid,
  meta jsonb,
  created_at timestamptz not null default now()
);

create index if not exists instance_events_instance_idx on public.instance_events (instance_id);
create index if not exists instance_events_to_user_idx on public.instance_events (to_user_id);

-- ---------- marketplace ----------

create table if not exists public.marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  instance_id uuid not null unique references public.chip_instances (id) on delete restrict,
  seller_id uuid not null references public.profiles (id) on delete cascade,
  price numeric(14,2) not null check (price > 0),
  status text not null default 'listed' check (status in ('listed','sold','cancelled')),
  listed_at timestamptz not null default now(),
  sold_at timestamptz,
  cancelled_at timestamptz
);

create index if not exists marketplace_listings_status_idx on public.marketplace_listings (status);
create index if not exists marketplace_listings_seller_idx on public.marketplace_listings (seller_id);

create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  instance_id uuid not null references public.chip_instances (id) on delete restrict,
  listing_id uuid references public.marketplace_listings (id) on delete set null,
  chip_id uuid not null references public.chips (id),
  buyer_id uuid not null references public.profiles (id),
  seller_id uuid references public.profiles (id),
  amount numeric(14,2) not null,
  fee numeric(14,2) not null default 0,
  type text not null check (type in ('shop','marketplace')),
  created_at timestamptz not null default now()
);

create index if not exists purchases_chip_idx on public.purchases (chip_id);
create index if not exists purchases_buyer_idx on public.purchases (buyer_id);
create index if not exists purchases_listing_idx on public.purchases (listing_id);

-- ---------- favs ----------

create table if not exists public.favorites (
  user_id uuid not null references public.profiles (id) on delete cascade,
  chip_id uuid not null references public.chips (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, chip_id)
);

-- ---------- packs ----------

create table if not exists public.packs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  image_url text,
  price numeric(14,2) not null check (price >= 0),
  status text not null default 'draft' check (status in ('draft','active','paused','ended')),
  available_count integer check (available_count is null or available_count >= 0),
  opened_count integer not null default 0 check (opened_count >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  current_version integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pack_versions (
  id uuid primary key default gen_random_uuid(),
  pack_id uuid not null references public.packs (id) on delete cascade,
  version integer not null,
  config jsonb not null,
  created_at timestamptz not null default now(),
  unique (pack_id, version)
);

-- pack_items: chips inside a version, grouped by tier (index in config.tiers)
create table if not exists public.pack_items (
  id uuid primary key default gen_random_uuid(),
  pack_version_id uuid not null references public.pack_versions (id) on delete cascade,
  tier_id integer not null,
  chip_id uuid not null references public.chips (id),
  weight numeric(12,4) not null check (weight > 0),
  unique (pack_version_id, tier_id, chip_id)
);

create index if not exists pack_items_version_idx on public.pack_items (pack_version_id);

-- ---------- trades ----------

create table if not exists public.trades (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  initiator_id uuid not null references public.profiles (id),
  partner_id uuid references public.profiles (id),
  status text not null default 'pending' check (status in ('pending','completed','cancelled')),
  wants jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  expires_at timestamptz not null default (now() + interval '7 days')
);

create index if not exists trades_initiator_idx on public.trades (initiator_id);

create table if not exists public.trade_items (
  id uuid primary key default gen_random_uuid(),
  trade_id uuid not null references public.trades (id) on delete cascade,
  instance_id uuid not null unique references public.chip_instances (id) on delete restrict,
  giver_id uuid not null references public.profiles (id),
  created_at timestamptz not null default now()
);

-- ---------- upgrades ----------

create table if not exists public.upgrades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id),
  source_instance_id uuid not null references public.chip_instances (id),
  target_chip_id uuid not null references public.chips (id),
  balance_spent numeric(14,2) not null default 0 check (balance_spent >= 0),
  chance numeric(5,2) not null check (chance >= 0 and chance <= 100),
  created_at timestamptz not null default now()
);

create table if not exists public.upgrade_attempts (
  id uuid primary key default gen_random_uuid(),
  upgrade_id uuid not null references public.upgrades (id) on delete cascade,
  success boolean not null,
  result_instance_id uuid references public.chip_instances (id),
  rolled_at timestamptz not null default now()
);

create index if not exists upgrades_user_idx on public.upgrades (user_id);

-- ---------- money ----------

create table if not exists public.balance_transactions (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.profiles (id),
  type text not null check (type in
    ('deposit','withdraw','purchase','sale','pack','upgrade','promo',
     'admin_grant','admin_remove','refund','trade','marketplace_buy')),
  amount numeric(14,2) not null,
  balance_before numeric(14,2) not null,
  balance_after numeric(14,2) not null,
  status text not null default 'completed' check (status in ('pending','completed','rejected','cancelled')),
  reference_type text,
  reference_id text,
  description text,
  admin_id uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists balance_transactions_user_idx on public.balance_transactions (user_id);

-- ---------- promo ----------

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  bonus_type text not null check (bonus_type in ('percent','fixed')),
  bonus_value numeric(14,2) not null check (bonus_value > 0),
  max_uses integer not null default 0 check (max_uses >= 0),
  per_user_limit integer not null default 1 check (per_user_limit >= 1),
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default true,
  used_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promo_code_uses (
  id uuid primary key default gen_random_uuid(),
  promo_code_id uuid not null references public.promo_codes (id) on delete cascade,
  user_id uuid not null references public.profiles (id),
  amount numeric(14,2) not null,
  balance_transaction_id bigint references public.balance_transactions (id),
  created_at timestamptz not null default now()
);

create index if not exists promo_uses_user_idx on public.promo_code_uses (user_id);

-- ---------- audit ----------

create table if not exists public.admin_audit_logs (
  id bigint generated always as identity primary key,
  admin_id uuid not null references public.profiles (id),
  action text not null,
  entity text not null,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  ip text,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_idx on public.admin_audit_logs (created_at desc);

-- ---------- triggers ----------

create or replace function public.touch_updated_at()
returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated on public.profiles;
create trigger profiles_updated before update on public.profiles
  for each row execute procedure public.touch_updated_at();

drop trigger if exists collections_updated on public.collections;
create trigger collections_updated before update on public.collections
  for each row execute procedure public.touch_updated_at();

drop trigger if exists chips_updated on public.chips;
create trigger chips_updated before update on public.chips
  for each row execute procedure public.touch_updated_at();

drop trigger if exists packs_updated on public.packs;
create trigger packs_updated before update on public.packs
  for each row execute procedure public.touch_updated_at();

drop trigger if exists promo_codes_updated on public.promo_codes;
create trigger promo_codes_updated before update on public.promo_codes
  for each row execute procedure public.touch_updated_at();

-- ---------- convenience view: inventory ----------

create or replace view public.inventory
with (security_invoker = on) as
select
  ci.id,
  ci.chip_id,
  ci.serial,
  ci.owner_id,
  ci.status,
  ci.acquired_at,
  ci.acquired_via,
  ci.locked_until,
  c.name as chip_name,
  c.number as chip_number,
  c.image_url,
  c.image_crop,
  c.base_price,
  c.collection_id,
  col.name as collection_name,
  col.slug as collection_slug,
  col.total_minted as collection_total,
  col.sold_count as collection_sold,
  col.status as collection_status,
  r.slug as rarity_slug,
  r.name as rarity_name,
  r.color as rarity_color,
  r.sort_order as rarity_order,
  l.name as level_name,
  l.slug as level_slug,
  l.sort_order as level_order
from public.chip_instances ci
join public.chips c on c.id = ci.chip_id
join public.collections col on col.id = c.collection_id
join public.rarities r on r.id = c.rarity_id
join public.levels l on l.id = c.level_id;


-- ============================================================
-- ЧАСТЬ 2: БИЗНЕС-ФУНКЦИИ (002_functions.sql)
-- ============================================================

-- ---------- helpers ----------

create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin' and not p.is_banned
  );
$$;

-- check currently signed-in user; raises if missing/banned
create or replace function public.require_user()
returns uuid
language plpgsql stable security definer set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_user public.profiles%rowtype;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;
  select * into v_user from public.profiles where id = v_uid;
  if not found then
    raise exception 'profile_not_found';
  end if;
  if v_user.is_banned then
    raise exception 'account_banned';
  end if;
  return v_uid;
end;
$$;

-- lock user row FOR UPDATE (must be called inside a transaction)
create or replace function public.lock_user(p_uid uuid)
returns public.profiles
language plpgsql security definer set search_path = public
as $$
declare
  v_user public.profiles%rowtype;
begin
  select * into v_user from public.profiles where id = p_uid for update;
  if not found then
    raise exception 'profile_not_found';
  end if;
  if v_user.is_banned then
    raise exception 'account_banned';
  end if;
  return v_user;
end;
$$;

-- insert an instance + event
create or replace function public.mint_instance(
  p_chip_id uuid,
  p_owner uuid,
  p_via text,
  p_lock_days integer default 7
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_chip public.chips%rowtype;
  v_col public.collections%rowtype;
  v_serial integer;
  v_instance_id uuid;
begin
  select * into v_chip from public.chips where id = p_chip_id for update;
  if not found then raise exception 'chip_not_found'; end if;
  if v_chip.status <> 'active' then raise exception 'chip_not_available'; end if;
  if v_chip.sold_count >= v_chip.total_minted then raise exception 'chip_sold_out'; end if;

  select * into v_col from public.collections where id = v_chip.collection_id for update;
  if not found then raise exception 'collection_not_found'; end if;
  if v_col.status not in ('active','pending') then raise exception 'collection_not_available'; end if;
  if v_col.sold_count >= v_col.total_minted then raise exception 'collection_sold_out'; end if;

  v_serial := v_chip.sold_count + 1;

  update public.chips set sold_count = sold_count + 1 where id = v_chip.id;
  update public.collections
     set sold_count = sold_count + 1,
         status = case when sold_count + 1 >= total_minted then 'sold_out' else status end
   where id = v_col.id;

  insert into public.chip_instances (chip_id, serial, owner_id, status, acquired_at, acquired_via, locked_until)
  values (p_chip_id, v_serial, p_owner, 'owned', now(), p_via, now() + make_interval(days => p_lock_days))
  returning id into v_instance_id;

  insert into public.instance_events (instance_id, event, to_user_id, meta)
  values (v_instance_id, 'minted', p_owner, jsonb_build_object('via', p_via, 'serial', v_serial));

  return v_instance_id;
end;
$$;

-- transfer instance to a new owner; relock = reset the 7-day lock
create or replace function public.transfer_instance(
  p_instance_id uuid,
  p_new_owner uuid,
  p_via text,
  p_relock boolean,
  p_lock_days integer default 7
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_inst public.chip_instances%rowtype;
  v_old_owner uuid;
begin
  select * into v_inst from public.chip_instances where id = p_instance_id for update;
  if not found then raise exception 'instance_not_found'; end if;
  v_old_owner := v_inst.owner_id;

  update public.chip_instances
     set owner_id = p_new_owner,
         status = 'owned',
         acquired_at = case when p_relock then now() else acquired_at end,
         acquired_via = case when p_relock then p_via else acquired_via end,
         locked_until = case when p_relock then now() + make_interval(days => p_lock_days) else locked_until end
   where id = p_instance_id;

  insert into public.instance_events (instance_id, event, from_user_id, to_user_id, meta)
  values (p_instance_id, 'transfer', v_old_owner, p_new_owner,
          jsonb_build_object('via', p_via, 'relocked', p_relock));
end;
$$;

-- -------- sell status --------
-- returns jsonb { allowed, reason, remaining_seconds, listing_id }
-- allowed when: owned by caller, no active listing, 7-day lock passed, collection sold out
create or replace function public.sell_status(p_instance_id uuid)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_inst public.chip_instances%rowtype;
  v_chip public.chips%rowtype;
  v_col public.collections%rowtype;
  v_listing_id uuid;
  v_remaining bigint;
begin
  select * into v_inst from public.chip_instances where id = p_instance_id;
  if not found then return jsonb_build_object('allowed', false, 'reason', 'not_found'); end if;
  if v_inst.owner_id <> v_uid then return jsonb_build_object('allowed', false, 'reason', 'not_owner'); end if;
  if v_inst.status not in ('owned','listed') then return jsonb_build_object('allowed', false, 'reason', 'invalid_status'); end if;

  select id into v_listing_id from public.marketplace_listings
   where instance_id = p_instance_id and status = 'listed';
  if v_listing_id is not null then
    return jsonb_build_object('allowed', false, 'reason', 'already_listed', 'listing_id', v_listing_id);
  end if;

  v_remaining := greatest(0, floor(extract(epoch from (coalesce(v_inst.locked_until, now()) - now()))));
  if v_remaining > 0 then
    return jsonb_build_object('allowed', false, 'reason', 'locked',
      'remaining_seconds', v_remaining);
  end if;

  select * into v_chip from public.chips where id = v_inst.chip_id;
  select * into v_col from public.collections where id = v_chip.collection_id;
  if v_col.sold_count < v_col.total_minted then
    return jsonb_build_object('allowed', false, 'reason', 'collection_not_sold_out');
  end if;

  return jsonb_build_object('allowed', true);
end;
$$;

-- ============================================================
-- SHOP
-- ============================================================

create or replace function public.buy_chip(p_chip_id uuid)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_user public.profiles%rowtype;
  v_chip public.chips%rowtype;
  v_price numeric(14,2);
  v_instance_id uuid;
begin
  v_user := public.lock_user(v_uid);

  select * into v_chip from public.chips where id = p_chip_id for update;
  if not found then raise exception 'chip_not_found'; end if;
  if v_chip.status <> 'active' then raise exception 'chip_not_available'; end if;

  v_price := v_chip.base_price;
  if v_user.balance < v_price then raise exception 'insufficient_balance'; end if;

  update public.profiles set balance = balance - v_price where id = v_uid;

  v_instance_id := public.mint_instance(v_chip.id, v_uid, 'shop', 7);

  insert into public.purchases (instance_id, chip_id, buyer_id, amount, fee, type)
  values (v_instance_id, v_chip.id, v_uid, v_price, 0, 'shop');

  insert into public.balance_transactions
    (user_id, type, amount, balance_before, balance_after, reference_type, reference_id, description)
  values
    (v_uid, 'purchase', -v_price, v_user.balance, v_user.balance - v_price,
     'purchase', v_instance_id::text,
     'Покупка в магазине: ' || v_chip.name);

  return v_instance_id;
end;
$$;

-- ============================================================
-- PACKS (server-side weighted random)
-- ============================================================

create or replace function public.open_pack(p_pack_id uuid)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_user public.profiles%rowtype;
  v_pack public.packs%rowtype;
  v_ver public.pack_versions%rowtype;
  v_tiers jsonb;
  v_tier jsonb;
  v_tier_weight numeric(12,4);
  v_roll numeric(12,4);
  v_acc numeric(12,4);
  v_tier_id integer;
  v_item record;
  v_items_total numeric(12,4);
  v_weight_acc numeric(12,4);
  v_choice record;
  v_instance_id uuid;
  v_price numeric(14,2);
begin
  v_user := public.lock_user(v_uid);

  select * into v_pack from public.packs where id = p_pack_id for update;
  if not found then raise exception 'pack_not_found'; end if;
  if v_pack.status <> 'active' then raise exception 'pack_not_active'; end if;
  if v_pack.starts_at is not null and v_pack.starts_at > now() then raise exception 'pack_not_started'; end if;
  if v_pack.ends_at is not null and v_pack.ends_at < now() then raise exception 'pack_ended'; end if;
  if v_pack.available_count is not null and v_pack.opened_count >= v_pack.available_count then
    raise exception 'pack_sold_out';
  end if;
  if v_pack.current_version = 0 then raise exception 'pack_no_version'; end if;

  v_price := v_pack.price;
  if v_user.balance < v_price then raise exception 'insufficient_balance'; end if;

  select * into v_ver from public.pack_versions
   where pack_id = p_pack_id and version = v_pack.current_version;
  if not found then raise exception 'pack_no_version'; end if;

  -- 1) pick tier by weight
  v_tiers := v_ver.config -> 'tiers';
  if jsonb_array_length(v_tiers) = 0 then raise exception 'pack_empty_config'; end if;

  v_roll := random() * 100.0;
  v_acc := 0;
  v_tier_id := null;
  for v_tier in select * from jsonb_array_elements(v_tiers) loop
    v_tier_weight := (v_tier ->> 'weight')::numeric(12,4);
    v_acc := v_acc + v_tier_weight;
    if v_roll < v_acc then
      v_tier_id := (v_tier ->> 'tier_id')::integer;
      exit;
    end if;
  end loop;
  if v_tier_id is null then
    -- rounding guard: pick the last tier
    v_tier := (select t from jsonb_array_elements(v_tiers) t order by (t ->> 'tier_id')::integer desc limit 1);
    v_tier_id := (v_tier ->> 'tier_id')::integer;
  end if;

  -- 2) pick a chip inside the tier by weight
  select coalesce(sum(weight), 0) into v_items_total
    from public.pack_items where pack_version_id = v_ver.id and tier_id = v_tier_id;
  if v_items_total <= 0 then raise exception 'pack_tier_empty'; end if;

  v_roll := random() * v_items_total;
  v_weight_acc := 0;
  v_choice := null;
  for v_item in
    select i.chip_id, i.weight from public.pack_items i
     where i.pack_version_id = v_ver.id and i.tier_id = v_tier_id
     order by i.id
  loop
    v_weight_acc := v_weight_acc + v_item.weight;
    if v_roll < v_weight_acc then
      v_choice := v_item;
      exit;
    end if;
  end loop;
  if v_choice is null then
    select i.chip_id, i.weight into v_choice from public.pack_items i
     where i.pack_version_id = v_ver.id and i.tier_id = v_tier_id
     order by i.id desc limit 1;
  end if;

  -- chip must be in stock; fallback: try any in-stock chip in tier
  begin
    v_instance_id := public.mint_instance(v_choice.chip_id, v_uid, 'pack', 7);
  exception when others then
    null;
  end;
  if v_instance_id is null then
    for v_item in
      select i.chip_id, i.weight from public.pack_items i
       where i.pack_version_id = v_ver.id and i.tier_id = v_tier_id
       and exists (select 1 from public.chips c
                   where c.id = i.chip_id and c.status = 'active'
                     and c.sold_count < c.total_minted)
       order by i.weight desc
    loop
      begin
        v_instance_id := public.mint_instance(v_item.chip_id, v_uid, 'pack', 7);
        exit;
      exception when others then
        null;
      end;
    end loop;
  end if;
  if v_instance_id is null then raise exception 'pack_no_chips'; end if;

  update public.packs set opened_count = opened_count + 1 where id = p_pack_id;
  update public.profiles set balance = balance - v_price where id = v_uid;

  insert into public.balance_transactions
    (user_id, type, amount, balance_before, balance_after, reference_type, reference_id, description)
  values
    (v_uid, 'pack', -v_price, v_user.balance, v_user.balance - v_price,
     'pack', v_pack.id::text, 'Открытие пака: ' || v_pack.name);

  return v_instance_id;
end;
$$;

-- ============================================================
-- MARKETPLACE
-- ============================================================

create or replace function public.create_listing(p_instance_id uuid, p_price numeric(14,2))
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_inst public.chip_instances%rowtype;
  v_status jsonb := public.sell_status(p_instance_id);
  v_listing_id uuid;
begin
  if p_price <= 0 then raise exception 'invalid_price'; end if;
  if not (v_status ->> 'allowed')::boolean then
    raise exception 'sale_not_allowed:%', v_status ->> 'reason';
  end if;

  select * into v_inst from public.chip_instances where id = p_instance_id for update;
  if v_inst.owner_id <> v_uid then raise exception 'not_owner'; end if;

  update public.chip_instances set status = 'listed' where id = p_instance_id;

  insert into public.marketplace_listings (instance_id, seller_id, price)
  values (p_instance_id, v_uid, p_price)
  returning id into v_listing_id;

  insert into public.instance_events (instance_id, event, actor_user_id, meta)
  values (p_instance_id, 'listed', v_uid, jsonb_build_object('listing_id', v_listing_id, 'price', p_price));

  return v_listing_id;
end;
$$;

create or replace function public.cancel_listing(p_listing_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_listing public.marketplace_listings%rowtype;
begin
  select * into v_listing from public.marketplace_listings where id = p_listing_id for update;
  if not found then raise exception 'listing_not_found'; end if;
  if v_listing.seller_id <> v_uid and not public.is_admin() then raise exception 'not_owner'; end if;
  if v_listing.status <> 'listed' then raise exception 'listing_not_active'; end if;

  update public.marketplace_listings
     set status = 'cancelled', cancelled_at = now()
   where id = p_listing_id;
  update public.chip_instances set status = 'owned' where id = v_listing.instance_id;

  insert into public.instance_events (instance_id, event, actor_user_id, meta)
  values (v_listing.instance_id, 'unlisted', v_uid, jsonb_build_object('listing_id', p_listing_id));
end;
$$;

create or replace function public.buy_listing(p_listing_id uuid)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_listing public.marketplace_listings%rowtype;
  v_buyer public.profiles%rowtype;
  v_seller public.profiles%rowtype;
  v_fee numeric(14,2);
  v_amount numeric(14,2);
begin
  select * into v_listing from public.marketplace_listings where id = p_listing_id for update;
  if not found then raise exception 'listing_not_found'; end if;
  if v_listing.status <> 'listed' then raise exception 'listing_not_active'; end if;
  if v_listing.seller_id = v_uid then raise exception 'cannot_buy_own'; end if;

  v_buyer := public.lock_user(v_uid);
  v_seller := public.lock_user(v_listing.seller_id);

  v_amount := v_listing.price;
  select coalesce((select (value ->> 'fee_percent')::numeric(14,2) from public.settings where key = 'marketplace')
                  , 0) into v_fee;
  if v_fee < 0 or v_fee > 100 then v_fee := 0; end if;
  v_fee := round(v_amount * v_fee / 100, 2);

  if v_buyer.balance < v_amount then raise exception 'insufficient_balance'; end if;

  update public.profiles set balance = balance - v_amount where id = v_uid;
  update public.profiles set balance = balance + (v_amount - v_fee) where id = v_listing.seller_id;

  update public.marketplace_listings
     set status = 'sold', sold_at = now()
   where id = p_listing_id;

  perform public.transfer_instance(v_listing.instance_id, v_uid, 'marketplace', true, 7);

  insert into public.purchases (instance_id, listing_id, chip_id, buyer_id, seller_id, amount, fee, type)
  select v_listing.instance_id, v_listing.id, ci.chip_id, v_uid, v_listing.seller_id, v_amount, v_fee, 'marketplace'
    from public.chip_instances ci where ci.id = v_listing.instance_id;

  insert into public.balance_transactions
    (user_id, type, amount, balance_before, balance_after, reference_type, reference_id, description)
  values
    (v_uid, 'marketplace_buy', -v_amount, v_buyer.balance, v_buyer.balance - v_amount,
     'listing', p_listing_id::text, 'Покупка на торговой площадке'),
    (v_listing.seller_id, 'sale', v_amount - v_fee, v_seller.balance, v_seller.balance + (v_amount - v_fee),
     'listing', p_listing_id::text, 'Продажа на торговой площадке');

  return v_listing.instance_id;
end;
$$;

-- ============================================================
-- TRADES (lock transfers with the item)
-- ============================================================

create or replace function public.create_trade(
  p_instance_ids uuid[],
  p_want_chip_ids uuid[],
  p_code text
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_instance_id uuid;
  v_chip_id uuid;
  v_trade_id uuid;
  v_code text := upper(coalesce(nullif(p_code,''), ''));
begin
  if array_length(p_instance_ids, 1) is null then raise exception 'no_items'; end if;
  if array_length(p_want_chip_ids, 1) is null then raise exception 'no_wants'; end if;
  if v_code = '' then
    v_code := upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 8));
  end if;
  if exists (select 1 from public.trades where code = v_code and status = 'pending') then
    raise exception 'code_taken';
  end if;

  insert into public.trades (code, initiator_id, wants)
  values (v_code, v_uid, to_jsonb(p_want_chip_ids))
  returning id into v_trade_id;

  foreach v_instance_id in array p_instance_ids loop
    if not exists (
      select 1 from public.chip_instances ci
       where ci.id = v_instance_id and ci.owner_id = v_uid and ci.status = 'owned'
    ) then
      raise exception 'not_ownable:%', v_instance_id;
    end if;
    insert into public.trade_items (trade_id, instance_id, giver_id)
    values (v_trade_id, v_instance_id, v_uid);
  end loop;

  -- block instances from being listed/sold while pending
  update public.chip_instances set status = 'traded' where id = any(p_instance_ids);

  return v_trade_id;
end;
$$;

-- partner accepts: their chips swap with initiator's chips
create or replace function public.accept_trade(p_code text, p_instance_ids uuid[])
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_trade public.trades%rowtype;
  v_init_items record;
  v_partner_item uuid;
  v_chip_id uuid;
  v_ok boolean;
  v_instance_id uuid;
  v_pending uuid[];
begin
  select * into v_trade from public.trades where upper(code) = upper(p_code) for update;
  if not found then raise exception 'trade_not_found'; end if;
  if v_trade.status <> 'pending' then raise exception 'trade_not_pending'; end if;
  if v_trade.initiator_id = v_uid then raise exception 'cannot_accept_own'; end if;
  if v_trade.expires_at < now() then raise exception 'trade_expired'; end if;
  if array_length(p_instance_ids, 1) <> (select count(*) from public.trade_items where trade_id = v_trade.id) then
    raise exception 'items_count_mismatch';
  end if;

  -- every partner instance must exist, be owned, be 'owned' status
  foreach v_instance_id in array p_instance_ids loop
    if not exists (
      select 1 from public.chip_instances ci
       where ci.id = v_instance_id and ci.owner_id = v_uid and ci.status = 'owned'
    ) then
      raise exception 'not_ownable:%', v_instance_id;
    end if;
  end loop;

  -- lock all involved instances in id order (avoid deadlocks)
  for v_instance_id in
    select i.instance_id from public.trade_items i where i.trade_id = v_trade.id
    union
    select unnest(p_instance_ids)
    order by 1
  loop
    select 1 into v_ok from public.chip_instances where id = v_instance_id for update;
    if not found then raise exception 'instance_not_found'; end if;
  end loop;

  -- initiator side
  for v_init_items in
    select i.instance_id, ci.chip_id from public.trade_items i
    join public.chip_instances ci on ci.id = i.instance_id
    where i.trade_id = v_trade.id
  loop
    perform public.transfer_instance(v_init_items.instance_id, v_uid, 'trade', false);
  end loop;

  -- partner side: give any owned chip; if the initiator asked specific chips, map by order
  v_pending := p_instance_ids;
  for v_init_items in
    select i.instance_id, ci.chip_id from public.trade_items i
    join public.chip_instances ci on ci.id = i.instance_id
    where i.trade_id = v_trade.id
  loop
    v_instance_id := (select unnest(v_pending) order by 1 limit 1);
    v_pending := array_remove(v_pending, v_instance_id);
    perform public.transfer_instance(v_instance_id, v_trade.initiator_id, 'trade', false);
  end loop;

  update public.trades set status = 'completed', partner_id = v_uid, completed_at = now()
   where id = v_trade.id;

  insert into public.balance_transactions
    (user_id, type, amount, balance_before, balance_after, description)
  values
    (v_uid, 'trade', 0, (select balance from public.profiles where id = v_uid),
     (select balance from public.profiles where id = v_uid), 'Обмен с ' || v_trade.code),
    (v_trade.initiator_id, 'trade', 0, (select balance from public.profiles where id = v_trade.initiator_id),
     (select balance from public.profiles where id = v_trade.initiator_id), 'Обмен с ' || v_trade.code);

  return v_trade.id;
end;
$$;

create or replace function public.cancel_trade(p_trade_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_trade public.trades%rowtype;
begin
  select * into v_trade from public.trades where id = p_trade_id for update;
  if not found then raise exception 'trade_not_found'; end if;
  if v_trade.initiator_id <> v_uid and not public.is_admin() then raise exception 'not_owner'; end if;
  if v_trade.status <> 'pending' then raise exception 'trade_not_pending'; end if;

  update public.trades set status = 'cancelled' where id = p_trade_id;
  update public.chip_instances set status = 'owned'
   where id in (select instance_id from public.trade_items where trade_id = p_trade_id);
end;
$$;

-- ============================================================
-- UPGRADES (chance computed + rolled on server)
-- ============================================================

create or replace function public.upgrade_chip(
  p_source_instance_id uuid,
  p_target_chip_id uuid,
  p_balance_spent numeric(14,2)
)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_user public.profiles%rowtype;
  v_source public.chip_instances%rowtype;
  v_source_chip public.chips%rowtype;
  v_target public.chips%rowtype;
  v_source_value numeric(14,2);
  v_target_value numeric(14,2);
  v_ratio numeric(14,4);
  v_chance numeric(5,2);
  v_rolled numeric;
  v_success boolean;
  v_result_instance_id uuid;
  v_upgrade_id uuid;
  v_balance_after numeric(14,2);
  v_pvp numeric(14,2);
begin
  if p_balance_spent < 0 then raise exception 'invalid_amount'; end if;

  v_user := public.lock_user(v_uid);

  select * into v_source from public.chip_instances where id = p_source_instance_id for update;
  if not found then raise exception 'instance_not_found'; end if;
  if v_source.owner_id <> v_uid then raise exception 'not_owner'; end if;
  if v_source.status not in ('owned','traded') then raise exception 'invalid_status'; end if;

  select * into v_source_chip from public.chips where id = v_source.chip_id;
  select * into v_target from public.chips where id = p_target_chip_id for update;
  if not found then raise exception 'chip_not_found'; end if;
  if v_target.status <> 'active' then raise exception 'chip_not_available'; end if;

  select coalesce((select (value ->> 'upgrade_source_multiplier')::numeric(14,4) from public.settings where key = 'economy'), 0.9)
    into v_pvp;
  v_source_value := round(v_source_chip.base_price * v_pvp, 2);
  v_target_value := v_target.base_price;
  if v_target_value <= 0 then raise exception 'target_free'; end if;

  v_ratio := (v_source_value + p_balance_spent) / v_target_value;
  v_chance := greatest(1, least(95, round(v_ratio * 100, 2)));

  if p_balance_spent > v_user.balance then raise exception 'insufficient_balance'; end if;
  if p_balance_spent > 0 then
    update public.profiles set balance = balance - p_balance_spent where id = v_uid;
    v_balance_after := v_user.balance - p_balance_spent;
  else
    v_balance_after := v_user.balance;
  end if;

  insert into public.upgrades (user_id, source_instance_id, target_chip_id, balance_spent, chance)
  values (v_uid, p_source_instance_id, p_target_chip_id, p_balance_spent, v_chance)
  returning id into v_upgrade_id;

  v_rolled := random() * 100;
  v_success := v_rolled < v_chance;

  if v_success then
    v_result_instance_id := public.mint_instance(v_target.id, v_uid, 'upgrade', 7);
    update public.chip_instances set status = 'upgraded' where id = p_source_instance_id;
  else
    update public.chip_instances set status = 'upgraded' where id = p_source_instance_id;
  end if;

  insert into public.upgrade_attempts (upgrade_id, success, result_instance_id)
  values (v_upgrade_id, v_success, v_result_instance_id);

  insert into public.instance_events (instance_id, event, actor_user_id, meta)
  values (p_source_instance_id, 'upgrade_burned', v_uid,
          jsonb_build_object('success', v_success, 'target_chip_id', p_target_chip_id,
                             'chance', v_chance, 'balance_spent', p_balance_spent));

  if p_balance_spent > 0 then
    insert into public.balance_transactions
      (user_id, type, amount, balance_before, balance_after, reference_type, reference_id, description)
    values
      (v_uid, 'upgrade', -p_balance_spent, v_user.balance, v_balance_after,
       'upgrade', v_upgrade_id::text, 'Апгрейд фишки');
  end if;

  return jsonb_build_object(
    'upgrade_id', v_upgrade_id,
    'success', v_success,
    'chance', v_chance,
    'result_instance_id', v_result_instance_id
  );
end;
$$;

-- ============================================================
-- MONEY / PROMO
-- ============================================================

create or replace function public.request_balance_change(p_type text, p_amount numeric(14,2))
returns bigint
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_user public.profiles%rowtype;
  v_txn_id bigint;
begin
  if p_type not in ('deposit','withdraw') then raise exception 'invalid_type'; end if;
  if p_amount <= 0 then raise exception 'invalid_amount'; end if;

  select * into v_user from public.profiles where id = v_uid for update;

  if p_type = 'withdraw' and v_user.balance < p_amount then
    raise exception 'insufficient_balance';
  end if;

  insert into public.balance_transactions
    (user_id, type, amount, balance_before, balance_after, status, description)
  values
    (v_uid, p_type, case when p_type = 'deposit' then p_amount else -p_amount end,
     v_user.balance, v_user.balance, 'pending',
     case when p_type = 'deposit' then 'Заявка на пополнение' else 'Заявка на вывод' end)
  returning id into v_txn_id;

  return v_txn_id;
end;
$$;

-- admin approves a pending deposit/withdraw request
create or replace function public.resolve_balance_request(p_txn_id bigint, p_approve boolean, p_admin_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_txn public.balance_transactions%rowtype;
  v_user public.profiles%rowtype;
begin
  if not exists (select 1 from public.profiles p
                 where p.id = p_admin_id and p.role = 'admin' and not p.is_banned) then
    raise exception 'forbidden';
  end if;

  select * into v_txn from public.balance_transactions where id = p_txn_id for update;
  if not found then raise exception 'txn_not_found'; end if;
  if v_txn.status <> 'pending' then raise exception 'txn_not_pending'; end if;

  if p_approve then
    v_user := public.lock_user(v_txn.user_id);
    if v_txn.type = 'withdraw' and v_user.balance < abs(v_txn.amount) then
      raise exception 'insufficient_balance';
    end if;
    update public.balance_transactions
       set status = 'completed',
           balance_before = v_user.balance,
           balance_after = v_user.balance + v_txn.amount,
           admin_id = p_admin_id
     where id = p_txn_id;
    update public.profiles set balance = balance + v_txn.amount where id = v_txn.user_id;
  else
    update public.balance_transactions
       set status = 'rejected', admin_id = p_admin_id
     where id = p_txn_id;
  end if;
end;
$$;

create or replace function public.activate_promo(p_code text)
returns numeric(14,2)
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_user public.profiles%rowtype;
  v_promo public.promo_codes%rowtype;
  v_uses integer;
  v_amount numeric(14,2);
  v_txn_id bigint;
begin
  select * into v_promo from public.promo_codes where upper(code) = upper(p_code) for update;
  if not found then raise exception 'promo_not_found'; end if;
  if not v_promo.is_active then raise exception 'promo_inactive'; end if;
  if v_promo.starts_at is not null and v_promo.starts_at > now() then raise exception 'promo_not_started'; end if;
  if v_promo.ends_at is not null and v_promo.ends_at < now() then raise exception 'promo_expired'; end if;
  if v_promo.max_uses > 0 and v_promo.used_count >= v_promo.max_uses then raise exception 'promo_used_up'; end if;

  select count(*) into v_uses from public.promo_code_uses
   where promo_code_id = v_promo.id and user_id = v_uid;
  if v_uses >= v_promo.per_user_limit then raise exception 'promo_claimed'; end if;

  select * into v_user from public.profiles where id = v_uid for update;

  if v_promo.bonus_type = 'percent' then
    v_amount := round(v_user.balance * v_promo.bonus_value / 100, 2);
  else
    v_amount := v_promo.bonus_value;
  end if;
  if v_amount <= 0 then raise exception 'promo_zero'; end if;

  update public.profiles set balance = balance + v_amount where id = v_uid;

  insert into public.balance_transactions
    (user_id, type, amount, balance_before, balance_after, reference_type, reference_id, description)
  values
    (v_uid, 'promo', v_amount, v_user.balance, v_user.balance + v_amount,
     'promo', v_promo.id::text, 'Промокод ' || v_promo.code)
  returning id into v_txn_id;

  insert into public.promo_code_uses (promo_code_id, user_id, amount, balance_transaction_id)
  values (v_promo.id, v_uid, v_amount, v_txn_id);

  update public.promo_codes set used_count = used_count + 1 where id = v_promo.id;

  return v_amount;
end;
$$;

-- ============================================================
-- FAVORITES
-- ============================================================

create or replace function public.toggle_favorite(p_chip_id uuid)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  v_uid uuid := public.require_user();
  v_fav boolean;
begin
  if exists (select 1 from public.favorites where user_id = v_uid and chip_id = p_chip_id) then
    delete from public.favorites where user_id = v_uid and chip_id = p_chip_id;
    v_fav := false;
  else
    insert into public.favorites (user_id, chip_id) values (v_uid, p_chip_id);
    v_fav := true;
  end if;
  return v_fav;
end;
$$;

-- ============================================================
-- ADMIN: pack version management (probabilities are validated here)
-- ============================================================

create or replace function public.create_pack_version(
  p_pack_id uuid,
  p_tiers jsonb,
  p_items jsonb,
  p_admin_id uuid
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  v_pack public.packs%rowtype;
  v_version int;
  v_ver_id uuid;
  v_tier jsonb;
  v_tier_sum numeric(12,4) := 0;
  v_rarity_id uuid;
  v_level_present boolean;
  v_level_mismatch int;
  v_items jsonb;
  v_item jsonb;
  v_item_sum numeric(12,4) := 0;
  v_chip public.chips%rowtype;
begin
  if not exists (select 1 from public.profiles p
                 where p.id = p_admin_id and p.role = 'admin' and not p.is_banned) then
    raise exception 'forbidden';
  end if;
  if jsonb_typeof(p_tiers) <> 'array' or jsonb_array_length(p_tiers) = 0 then
    raise exception 'tiers_empty';
  end if;

  -- validate tiers
  for v_tier in select * from jsonb_array_elements(p_tiers) loop
    if (v_tier ->> 'weight')::numeric(12,4) <= 0 then raise exception 'tier_weight_invalid'; end if;
    select id into v_rarity_id from public.rarities r where r.id = (v_tier ->> 'rarity_id')::uuid;
    if v_rarity_id is null then raise exception 'rarity_not_found'; end if;
    v_level_present := v_tier ? 'level_id' and (v_tier ->> 'level_id') is not null and (v_tier ->> 'level_id') <> '';
    if v_level_present and not exists (
      select 1 from public.levels l where l.id = (v_tier ->> 'level_id')::uuid
    ) then
      raise exception 'level_not_found';
    end if;
    v_tier_sum := v_tier_sum + (v_tier ->> 'weight')::numeric(12,4);
  end loop;
  if abs(v_tier_sum - 100) > 0.001 then raise exception 'tiers_sum_not_100:%', v_tier_sum; end if;

  select * into v_pack from public.packs where id = p_pack_id for update;
  if not found then raise exception 'pack_not_found'; end if;

  v_version := v_pack.current_version + 1;

  insert into public.pack_versions (pack_id, version, config)
  values (p_pack_id, v_version, jsonb_build_object('tiers', p_tiers, 'created_by', p_admin_id))
  returning id into v_ver_id;

  -- validate + insert items
  for v_tier in select * from jsonb_array_elements(p_tiers) loop
    v_items := coalesce(jsonb_path_query_array(p_items, format('$[*] ? (@.tier_id == %s)', (v_tier ->> 'tier_id')::int)::jsonpath), '[]'::jsonb);
    if jsonb_array_length(v_items) = 0 then
      delete from public.pack_versions where id = v_ver_id;
      raise exception 'tier_items_empty:%', v_tier ->> 'tier_id';
    end if;
    v_item_sum := 0;
    for v_item in select * from jsonb_array_elements(v_items) loop
      if (v_item ->> 'weight')::numeric(12,4) <= 0 then raise exception 'item_weight_invalid'; end if;
      select * into v_chip from public.chips where id = (v_item ->> 'chip_id')::uuid;
      if not found or v_chip.status <> 'active' then raise exception 'chip_invalid'; end if;
      if v_chip.rarity_id <> (v_tier ->> 'rarity_id')::uuid then
        raise exception 'chip_rarity_mismatch';
      end if;
      v_level_present := v_tier ? 'level_id' and (v_tier ->> 'level_id') is not null and (v_tier ->> 'level_id') <> '';
      if v_level_present and v_chip.level_id <> (v_tier ->> 'level_id')::uuid then
        raise exception 'chip_level_mismatch';
      end if;
      v_item_sum := v_item_sum + (v_item ->> 'weight')::numeric(12,4);

      insert into public.pack_items (pack_version_id, tier_id, chip_id, weight)
      values (v_ver_id, (v_tier ->> 'tier_id')::int, v_chip.id, (v_item ->> 'weight')::numeric(12,4));
    end loop;
    if abs(v_item_sum - 100) > 0.001 then
      delete from public.pack_versions where id = v_ver_id;
      raise exception 'items_sum_not_100:%', v_tier ->> 'tier_id';
    end if;
  end loop;

  update public.packs set current_version = v_version where id = p_pack_id;

  return v_ver_id;
end;
$$;

-- ============================================================
-- Permissions
-- ============================================================

revoke all on function public.is_admin() from public;
revoke all on function public.require_user() from public;
revoke all on function public.lock_user(uuid) from public;
revoke all on function public.mint_instance(uuid, uuid, text, integer) from public;
revoke all on function public.transfer_instance(uuid, uuid, text, boolean, integer) from public;
revoke all on function public.sell_status(uuid) from public;
revoke all on function public.buy_chip(uuid) from public;
revoke all on function public.open_pack(uuid) from public;
revoke all on function public.create_listing(uuid, numeric) from public;
revoke all on function public.cancel_listing(uuid) from public;
revoke all on function public.buy_listing(uuid) from public;
revoke all on function public.create_trade(uuid[], uuid[], text) from public;
revoke all on function public.accept_trade(text, uuid[]) from public;
revoke all on function public.cancel_trade(uuid) from public;
revoke all on function public.upgrade_chip(uuid, uuid, numeric) from public;
revoke all on function public.request_balance_change(text, numeric) from public;
revoke all on function public.resolve_balance_request(bigint, boolean, uuid) from public;
revoke all on function public.activate_promo(text) from public;
revoke all on function public.toggle_favorite(uuid) from public;
revoke all on function public.create_pack_version(uuid, jsonb, jsonb, uuid) from public;
revoke all on function public.touch_updated_at() from public;
revoke all on function public.handle_new_user() from public;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.sell_status(uuid) to authenticated;
grant execute on function public.buy_chip(uuid) to authenticated;
grant execute on function public.open_pack(uuid) to authenticated;
grant execute on function public.create_listing(uuid, numeric) to authenticated;
grant execute on function public.cancel_listing(uuid) to authenticated;
grant execute on function public.buy_listing(uuid) to authenticated;
grant execute on function public.create_trade(uuid[], uuid[], text) to authenticated;
grant execute on function public.accept_trade(text, uuid[]) to authenticated;
grant execute on function public.cancel_trade(uuid) to authenticated;
grant execute on function public.upgrade_chip(uuid, uuid, numeric) to authenticated;
grant execute on function public.request_balance_change(text, numeric) to authenticated;
grant execute on function public.resolve_balance_request(bigint, boolean, uuid) to authenticated;
grant execute on function public.activate_promo(text) to authenticated;
grant execute on function public.toggle_favorite(uuid) to authenticated;
grant execute on function public.create_pack_version(uuid, jsonb, jsonb, uuid) to authenticated;


-- ============================================================
-- ЧАСТЬ 3: RLS И STORAGE (003_rls.sql)
-- ============================================================

-- ---------- public profile table (no sensitive data) ----------

create table if not exists public.profiles_public (
  user_id uuid primary key references public.profiles (id) on delete cascade,
  account_id bigint,
  username text,
  avatar_url text,
  created_at timestamptz
);

create or replace function public.sync_profiles_public()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles_public (user_id, account_id, username, avatar_url, created_at)
  values (new.id, new.account_id, new.username, new.avatar_url, new.created_at)
  on conflict (user_id) do update set
    username = excluded.username,
    avatar_url = excluded.avatar_url;
  return new;
end;
$$;

drop trigger if exists profiles_public_sync on public.profiles;
create trigger profiles_public_sync
  after insert or update on public.profiles
  for each row execute procedure public.sync_profiles_public();

revoke all on function public.sync_profiles_public() from public;

-- ---------- explicit grants (Supabase default grants are reverted) ----------

revoke all on table
  public.rarities, public.levels, public.settings,
  public.profiles, public.profiles_public,
  public.collections, public.chips,
  public.chip_instances, public.instance_events,
  public.marketplace_listings, public.purchases,
  public.favorites,
  public.packs, public.pack_versions, public.pack_items,
  public.trades, public.trade_items,
  public.upgrades, public.upgrade_attempts,
  public.balance_transactions,
  public.promo_codes, public.promo_code_uses,
  public.admin_audit_logs
from anon, authenticated;

-- public catalog (anon + authenticated)
grant select on
  public.rarities, public.levels, public.settings,
  public.collections, public.chips,
  public.pack_versions, public.pack_items,
  public.marketplace_listings, public.purchases,
  public.instance_events,
  public.profiles_public
to anon, authenticated;

-- user-owned rows (authenticated only)
grant select on public.profiles to authenticated;
grant select, insert, delete on public.favorites to authenticated;
grant select on public.chip_instances to authenticated;
grant select on public.balance_transactions to authenticated;
grant select on public.promo_code_uses to authenticated;
grant select on public.trades to authenticated;
grant select on public.trade_items to authenticated;
grant select on public.upgrades to authenticated;
grant select on public.upgrade_attempts to authenticated;
grant select on public.inventory to authenticated;

-- username update (column-level: only this column is updatable by users)
grant update (username) on public.profiles to authenticated;

-- ---------- RLS enable (idempotent) ----------

alter table public.profiles enable row level security;
alter table public.profiles_public enable row level security;
alter table public.rarities enable row level security;
alter table public.levels enable row level security;
alter table public.settings enable row level security;
alter table public.collections enable row level security;
alter table public.chips enable row level security;
alter table public.chip_instances enable row level security;
alter table public.instance_events enable row level security;
alter table public.marketplace_listings enable row level security;
alter table public.purchases enable row level security;
alter table public.favorites enable row level security;
alter table public.packs enable row level security;
alter table public.pack_versions enable row level security;
alter table public.pack_items enable row level security;
alter table public.trades enable row level security;
alter table public.trade_items enable row level security;
alter table public.upgrades enable row level security;
alter table public.upgrade_attempts enable row level security;
alter table public.balance_transactions enable row level security;
alter table public.promo_codes enable row level security;
alter table public.promo_code_uses enable row level security;
alter table public.admin_audit_logs enable row level security;

-- ---------- policies ----------

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "profiles_public_select" on public.profiles_public;
create policy "profiles_public_select" on public.profiles_public
  for select using (true);

drop policy if exists "catalog_read" on public.rarities;
create policy "catalog_read" on public.rarities for select using (true);

drop policy if exists "catalog_read" on public.levels;
create policy "catalog_read" on public.levels for select using (true);

drop policy if exists "catalog_read" on public.settings;
create policy "catalog_read" on public.settings for select using (true);

drop policy if exists "collections_read" on public.collections;
create policy "collections_read" on public.collections
  for select using (status in ('active','sold_out','pending'));

drop policy if exists "chips_read" on public.chips;
create policy "chips_read" on public.chips
  for select using (status = 'active');

drop policy if exists "packs_read" on public.packs;
create policy "packs_read" on public.packs
  for select using (status = 'active');

drop policy if exists "pack_versions_read" on public.pack_versions;
create policy "pack_versions_read" on public.pack_versions
  for select using (exists (select 1 from public.packs p where p.id = pack_id and p.status = 'active'));

drop policy if exists "pack_items_read" on public.pack_items;
create policy "pack_items_read" on public.pack_items
  for select using (exists (
    select 1 from public.pack_versions pv
    join public.packs p on p.id = pv.pack_id
    where pv.id = pack_version_id and p.status = 'active'));

drop policy if exists "instances_select_own" on public.chip_instances;
create policy "instances_select_own" on public.chip_instances
  for select using (owner_id = auth.uid());

drop policy if exists "events_read" on public.instance_events;
create policy "events_read" on public.instance_events
  for select using (true);

drop policy if exists "listings_read" on public.marketplace_listings;
create policy "listings_read" on public.marketplace_listings
  for select using (status = 'listed');

drop policy if exists "purchases_read" on public.purchases;
create policy "purchases_read" on public.purchases
  for select using (buyer_id = auth.uid() or seller_id = auth.uid());

drop policy if exists "favs_own" on public.favorites;
create policy "favs_own" on public.favorites
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "trades_read" on public.trades;
create policy "trades_read" on public.trades
  for select using (
    status = 'pending'
    or initiator_id = auth.uid()
    or partner_id = auth.uid()
  );

drop policy if exists "trade_items_read" on public.trade_items;
create policy "trade_items_read" on public.trade_items
  for select using (exists (
    select 1 from public.trades t
    where t.id = trade_id
      and (t.status = 'pending' or t.initiator_id = auth.uid() or t.partner_id = auth.uid())));

drop policy if exists "upgrades_read" on public.upgrades;
create policy "upgrades_read" on public.upgrades
  for select using (user_id = auth.uid());

drop policy if exists "upgrade_attempts_read" on public.upgrade_attempts;
create policy "upgrade_attempts_read" on public.upgrade_attempts
  for select using (exists (
    select 1 from public.upgrades u where u.id = upgrade_id and u.user_id = auth.uid()));

drop policy if exists "txns_read" on public.balance_transactions;
create policy "txns_read" on public.balance_transactions
  for select using (user_id = auth.uid());

drop policy if exists "promo_uses_read" on public.promo_code_uses;
create policy "promo_uses_read" on public.promo_code_uses
  for select using (user_id = auth.uid());

-- ---------- storage ----------

insert into storage.buckets (id, name, public)
values ('chips', 'chips', true), ('packs', 'packs', true), ('collections', 'collections', true), ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "nuffy_public_read" on storage.objects;
create policy "nuffy_public_read" on storage.objects
  for select using (bucket_id in ('chips','packs','collections','avatars'));

drop policy if exists "nuffy_auth_insert" on storage.objects;
create policy "nuffy_auth_insert" on storage.objects
  for insert to authenticated
  with check (bucket_id in ('chips','packs','collections','avatars') and owner = auth.uid());

drop policy if exists "nuffy_auth_update" on storage.objects;
create policy "nuffy_auth_update" on storage.objects
  for update to authenticated
  using (bucket_id in ('chips','packs','collections','avatars') and owner = auth.uid());

drop policy if exists "nuffy_auth_delete" on storage.objects;
create policy "nuffy_auth_delete" on storage.objects
  for delete to authenticated
  using (bucket_id in ('chips','packs','collections','avatars') and owner = auth.uid());


-- ============================================================
-- ЧАСТЬ 4: ДЕМО-ДАННЫЕ (004_seed.sql)
-- Применяются один раз; повторный запуск пропускается.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.seed_state (
  key text primary key,
  applied_at timestamptz not null default now()
);

do $$
begin
  -- пропускаем, если демо-данные уже применены (или были посеяны ранее)
  if exists (select 1 from public.seed_state where key = 'demo_seed')
     or exists (select 1 from public.packs where current_version > 0) then
    raise notice 'NUFFY: демо-данные уже применены, пропуск';
    return;
  end if;

  -- ---------- rarities ----------

  insert into public.rarities (slug, name, color, sort_order) values
    ('common', 'Common', '#A8AFBB', 1),
    ('uncommon', 'Uncommon', '#47D38C', 2),
    ('rare', 'Rare', '#4FB3F0', 3),
    ('epic', 'Epic', '#A97CF8', 4),
    ('legendary', 'Legendary', '#F5C651', 5)
  on conflict (slug) do nothing;

  -- ---------- levels ----------

  insert into public.levels (name, slug, sort_order, color, multiplier) values
    ('Level 1', 'level-1', 1, '#9AA3B2', 1.0),
    ('Level 2', 'level-2', 2, '#A8AFBB', 1.5),
    ('Level 3', 'level-3', 3, '#C6CDD6', 2.2),
    ('Level 4', 'level-4', 4, '#E2E6EB', 3.4),
    ('Level 5', 'level-5', 5, '#F5C651', 5.0)
  on conflict (slug) do nothing;

  -- ---------- settings ----------

  insert into public.settings (key, value) values
    ('marketplace', '{"fee_percent": 0}'),
    ('economy', '{"upgrade_source_multiplier": 0.9}')
  on conflict (key) do update set value = excluded.value;

  -- ---------- collections ----------

  insert into public.collections (id, name, slug, description, total_minted, sold_count, released_at, status) values
    ('00000000-0000-0000-0000-000000000001', 'Neon Genesis', 'neon-genesis',
     'Первый тираж NUFFY. Неоновые существа цифрового города.', 1000, 830, now() - interval '30 days', 'active'),
    ('00000000-0000-0000-0000-000000000002', 'Obsidian Hall', 'obsidian-hall',
     'Тёмные фишки из глубины дворца обсидиана.', 1000, 690, now() - interval '21 days', 'active'),
    ('00000000-0000-0000-0000-000000000003', 'Verdant Era', 'verdant-era',
     'Эпоха зелени: лесные стражи и древние звери.', 1200, 810, now() - interval '14 days', 'active'),
    ('00000000-0000-0000-0000-000000000004', 'Solar Drift', 'solar-drift',
     'Распроданный тираж. Солнечная дрейфующая коллекция.', 500, 500, now() - interval '60 days', 'sold_out')
  on conflict (id) do nothing;

  -- ---------- chips (Neon Genesis) ----------

  insert into public.chips (id, collection_id, name, number, rarity_id, level_id, base_price, total_minted, sold_count, status) values
    ('10000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'Cyber Static', 1,
     (select id from rarities where slug='common'), (select id from levels where slug='level-1'), 60, 400, 320, 'active'),
    ('10000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'Glitch Pup', 2,
     (select id from rarities where slug='common'), (select id from levels where slug='level-2'), 90, 400, 300, 'active'),
    ('10000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001', 'Neon Bite', 3,
     (select id from rarities where slug='common'), (select id from levels where slug='level-2'), 120, 350, 250, 'active'),
    ('10000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000001', 'Circuit Fox', 4,
     (select id from rarities where slug='uncommon'), (select id from levels where slug='level-2'), 260, 240, 170, 'active'),
    ('10000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000001', 'Hyper Daisy', 5,
     (select id from rarities where slug='uncommon'), (select id from levels where slug='level-3'), 340, 220, 150, 'active'),
    ('10000000-0000-0000-0000-000000000006', '00000000-0000-0000-0000-000000000001', 'Prism Cat', 6,
     (select id from rarities where slug='rare'), (select id from levels where slug='level-3'), 900, 90, 55, 'active'),
    ('10000000-0000-0000-0000-000000000007', '00000000-0000-0000-0000-000000000001', 'Void Rabbit', 7,
     (select id from rarities where slug='rare'), (select id from levels where slug='level-4'), 1400, 70, 40, 'active'),
    ('10000000-0000-0000-0000-000000000008', '00000000-0000-0000-0000-000000000001', 'Chroma Seraph', 8,
     (select id from rarities where slug='epic'), (select id from levels where slug='level-4'), 3400, 40, 22, 'active'),
    ('10000000-0000-0000-0000-000000000009', '00000000-0000-0000-0000-000000000001', 'Neon Oracle', 9,
     (select id from rarities where slug='legendary'), (select id from levels where slug='level-5'), 12000, 10, 4, 'active')
  on conflict (id) do nothing;

  -- ---------- chips (Obsidian Hall) ----------

  insert into public.chips (id, collection_id, name, number, rarity_id, level_id, base_price, total_minted, sold_count, status) values
    ('10000000-0000-0000-0000-000000000011', '00000000-0000-0000-0000-000000000002', 'Ash Moth', 1,
     (select id from rarities where slug='common'), (select id from levels where slug='level-1'), 70, 380, 270, 'active'),
    ('10000000-0000-0000-0000-000000000012', '00000000-0000-0000-0000-000000000002', 'Iron Finch', 2,
     (select id from rarities where slug='common'), (select id from levels where slug='level-2'), 110, 360, 250, 'active'),
    ('10000000-0000-0000-0000-000000000013', '00000000-0000-0000-0000-000000000002', 'Marble Wolf', 3,
     (select id from rarities where slug='uncommon'), (select id from levels where slug='level-2'), 300, 200, 140, 'active'),
    ('10000000-0000-0000-0000-000000000014', '00000000-0000-0000-0000-000000000002', 'Quartz Doe', 4,
     (select id from rarities where slug='uncommon'), (select id from levels where slug='level-3'), 420, 180, 120, 'active'),
    ('10000000-0000-0000-0000-000000000015', '00000000-0000-0000-0000-000000000002', 'Basalt Owl', 5,
     (select id from rarities where slug='rare'), (select id from levels where slug='level-3'), 1050, 80, 48, 'active'),
    ('10000000-0000-0000-0000-000000000016', '00000000-0000-0000-0000-000000000002', 'Onyx Crow', 6,
     (select id from rarities where slug='rare'), (select id from levels where slug='level-4'), 1600, 60, 34, 'active'),
    ('10000000-0000-0000-0000-000000000017', '00000000-0000-0000-0000-000000000002', 'Obsidian Drake', 7,
     (select id from rarities where slug='epic'), (select id from levels where slug='level-4'), 3900, 30, 15, 'active'),
    ('10000000-0000-0000-0000-000000000018', '00000000-0000-0000-0000-000000000002', 'Crown of Ash', 8,
     (select id from rarities where slug='legendary'), (select id from levels where slug='level-5'), 15000, 8, 3, 'active')
  on conflict (id) do nothing;

  -- ---------- chips (Verdant Era) ----------

  insert into public.chips (id, collection_id, name, number, rarity_id, level_id, base_price, total_minted, sold_count, status) values
    ('10000000-0000-0000-0000-000000000021', '00000000-0000-0000-0000-000000000003', 'Sprout Beetle', 1,
     (select id from rarities where slug='common'), (select id from levels where slug='level-1'), 55, 450, 340, 'active'),
    ('10000000-0000-0000-0000-000000000022', '00000000-0000-0000-0000-000000000003', 'Moss Bunny', 2,
     (select id from rarities where slug='common'), (select id from levels where slug='level-2'), 95, 420, 300, 'active'),
    ('10000000-0000-0000-0000-000000000023', '00000000-0000-0000-0000-000000000003', 'Fern Heron', 3,
     (select id from rarities where slug='uncommon'), (select id from levels where slug='level-2'), 250, 240, 160, 'active'),
    ('10000000-0000-0000-0000-000000000024', '00000000-0000-0000-0000-000000000003', 'Amber Boar', 4,
     (select id from rarities where slug='uncommon'), (select id from levels where slug='level-3'), 380, 200, 130, 'active'),
    ('10000000-0000-0000-0000-000000000025', '00000000-0000-0000-0000-000000000003', 'Grove Lynx', 5,
     (select id from rarities where slug='rare'), (select id from levels where slug='level-3'), 980, 90, 50, 'active'),
    ('10000000-0000-0000-0000-000000000026', '00000000-0000-0000-0000-000000000003', 'Ember Stag', 6,
     (select id from rarities where slug='rare'), (select id from levels where slug='level-4'), 1500, 70, 38, 'active'),
    ('10000000-0000-0000-0000-000000000027', '00000000-0000-0000-0000-000000000003', 'Jade Wyrm', 7,
     (select id from rarities where slug='epic'), (select id from levels where slug='level-4'), 3600, 35, 17, 'active'),
    ('10000000-0000-0000-0000-000000000028', '00000000-0000-0000-0000-000000000003', 'Old Growth Titan', 8,
     (select id from rarities where slug='legendary'), (select id from levels where slug='level-5'), 13500, 10, 4, 'active')
  on conflict (id) do nothing;

  -- ---------- chips (Solar Drift — fully sold out) ----------

  insert into public.chips (id, collection_id, name, number, rarity_id, level_id, base_price, total_minted, sold_count, status) values
    ('10000000-0000-0000-0000-000000000031', '00000000-0000-0000-0000-000000000004', 'Dust Comet', 1,
     (select id from rarities where slug='common'), (select id from levels where slug='level-1'), 65, 200, 200, 'active'),
    ('10000000-0000-0000-0000-000000000032', '00000000-0000-0000-0000-000000000004', 'Solar Lark', 2,
     (select id from rarities where slug='common'), (select id from levels where slug='level-2'), 105, 180, 180, 'active'),
    ('10000000-0000-0000-0000-000000000033', '00000000-0000-0000-0000-000000000004', 'Magma Koi', 3,
     (select id from rarities where slug='uncommon'), (select id from levels where slug='level-2'), 290, 100, 100, 'active'),
    ('10000000-0000-0000-0000-000000000034', '00000000-0000-0000-0000-000000000004', 'Cinder Hare', 4,
     (select id from rarities where slug='uncommon'), (select id from levels where slug='level-3'), 400, 90, 90, 'active'),
    ('10000000-0000-0000-0000-000000000035', '00000000-0000-0000-0000-000000000004', 'Flare Condor', 5,
     (select id from rarities where slug='rare'), (select id from levels where slug='level-3'), 1100, 40, 40, 'active'),
    ('10000000-0000-0000-0000-000000000036', '00000000-0000-0000-0000-000000000004', 'Helios Lion', 6,
     (select id from rarities where slug='rare'), (select id from levels where slug='level-4'), 1700, 30, 30, 'active'),
    ('10000000-0000-0000-0000-000000000037', '00000000-0000-0000-0000-000000000004', 'Sunfall Kraken', 7,
     (select id from rarities where slug='epic'), (select id from levels where slug='level-4'), 4100, 15, 15, 'active'),
    ('10000000-0000-0000-0000-000000000038', '00000000-0000-0000-0000-000000000004', 'Heliarch', 8,
     (select id from rarities where slug='legendary'), (select id from levels where slug='level-5'), 16000, 5, 5, 'active')
  on conflict (id) do nothing;

  -- ---------- demo user (создаём ДО паков — им нужен admin) ----------

  insert into auth.users (id, email, encrypted_password, raw_user_meta_data, email_confirmed_at, created_at, updated_at)
  values (
    '30000000-0000-0000-0000-000000000001',
    'demo@nuffy.app',
    crypt('demo123456', gen_salt('bf')),
    '{"username": "demo"}',
    now(), now(), now()
  ) on conflict (id) do nothing;

  insert into public.profiles (id, username, balance)
  values (
    '30000000-0000-0000-0000-000000000001',
    'demo',
    5000
  )
  on conflict (id) do update set username = excluded.username, balance = excluded.balance;

  -- ---------- packs ----------

  insert into public.packs (id, name, description, price, status, available_count, opened_count, current_version, starts_at, ends_at) values
    ('20000000-0000-0000-0000-000000000001', 'Genesis Starter Pack',
     'Стартовый пак с фишками Neon Genesis. Шанс легендарки: 1.5%.',
     250, 'active', 5000, 0, 0, now() - interval '3 days', now() + interval '60 days'),
    ('20000000-0000-0000-0000-000000000002', 'Verdant Booster',
     'Бустер Verdant Era. Повышенный шанс редких фишек.',
     600, 'active', 2000, 0, 0, now() - interval '2 days', now() + interval '45 days')
  on conflict (id) do nothing;

  -- bootstrap: временно даём демо-юзеру роль admin для создания версий паков
  update public.profiles set role = 'admin' where id = '30000000-0000-0000-0000-000000000001';

  perform public.create_pack_version(
    '20000000-0000-0000-0000-000000000001',
    '[
      {"tier_id": 1, "name": "Common", "rarity_id": "' || (select id from public.rarities where slug='common') || '", "weight": 50},
      {"tier_id": 2, "name": "Uncommon", "rarity_id": "' || (select id from public.rarities where slug='uncommon') || '", "weight": 30},
      {"tier_id": 3, "name": "Rare", "rarity_id": "' || (select id from public.rarities where slug='rare') || '", "weight": 13},
      {"tier_id": 4, "name": "Epic", "rarity_id": "' || (select id from public.rarities where slug='epic') || '", "weight": 5.5},
      {"tier_id": 5, "name": "Legendary", "rarity_id": "' || (select id from public.rarities where slug='legendary') || '", "weight": 1.5}
    ]'::jsonb,
    '[
      {"tier_id": 1, "chip_id": "10000000-0000-0000-0000-000000000001", "weight": 40},
      {"tier_id": 1, "chip_id": "10000000-0000-0000-0000-000000000002", "weight": 35},
      {"tier_id": 1, "chip_id": "10000000-0000-0000-0000-000000000003", "weight": 25},
      {"tier_id": 2, "chip_id": "10000000-0000-0000-0000-000000000004", "weight": 55},
      {"tier_id": 2, "chip_id": "10000000-0000-0000-0000-000000000005", "weight": 45},
      {"tier_id": 3, "chip_id": "10000000-0000-0000-0000-000000000006", "weight": 60},
      {"tier_id": 3, "chip_id": "10000000-0000-0000-0000-000000000007", "weight": 40},
      {"tier_id": 4, "chip_id": "10000000-0000-0000-0000-000000000008", "weight": 100},
      {"tier_id": 5, "chip_id": "10000000-0000-0000-0000-000000000009", "weight": 100}
    ]'::jsonb,
    '30000000-0000-0000-0000-000000000001');

  perform public.create_pack_version(
    '20000000-0000-0000-0000-000000000002',
    '[
      {"tier_id": 1, "name": "Common", "rarity_id": "' || (select id from public.rarities where slug='common') || '", "weight": 40},
      {"tier_id": 2, "name": "Uncommon", "rarity_id": "' || (select id from public.rarities where slug='uncommon') || '", "weight": 30},
      {"tier_id": 3, "name": "Rare", "rarity_id": "' || (select id from public.rarities where slug='rare') || '", "weight": 20},
      {"tier_id": 4, "name": "Epic", "rarity_id": "' || (select id from public.rarities where slug='epic') || '", "weight": 8},
      {"tier_id": 5, "name": "Legendary", "rarity_id": "' || (select id from public.rarities where slug='legendary') || '", "weight": 2}
    ]'::jsonb,
    '[
      {"tier_id": 1, "chip_id": "10000000-0000-0000-0000-000000000021", "weight": 40},
      {"tier_id": 1, "chip_id": "10000000-0000-0000-0000-000000000022", "weight": 35},
      {"tier_id": 2, "chip_id": "10000000-0000-0000-0000-000000000023", "weight": 50},
      {"tier_id": 2, "chip_id": "10000000-0000-0000-0000-000000000024", "weight": 50},
      {"tier_id": 3, "chip_id": "10000000-0000-0000-0000-000000000025", "weight": 55},
      {"tier_id": 3, "chip_id": "10000000-0000-0000-0000-000000000026", "weight": 45},
      {"tier_id": 4, "chip_id": "10000000-0000-0000-0000-000000000027", "weight": 100},
      {"tier_id": 5, "chip_id": "10000000-0000-0000-0000-000000000028", "weight": 100}
    ]'::jsonb,
    '30000000-0000-0000-0000-000000000001');

  update public.profiles set role = 'user' where id = '30000000-0000-0000-0000-000000000001';

  -- ---------- demo inventory: одна продаваемая фишка (lock прошёл), две заблокированные, одна из пака ----------

  perform public.mint_instance('10000000-0000-0000-0000-000000000006', '30000000-0000-0000-0000-000000000001', 'shop');

  update public.chip_instances set locked_until = now() - interval '1 day'
   where chip_id = '10000000-0000-0000-0000-000000000006'
     and owner_id = '30000000-0000-0000-0000-000000000001';

  update public.chips set sold_count = sold_count - 1
   where id = '10000000-0000-0000-0000-000000000006';
  update public.collections set sold_count = sold_count - 1
   where id = '00000000-0000-0000-0000-000000000001';

  perform public.mint_instance('10000000-0000-0000-0000-000000000002', '30000000-0000-0000-0000-000000000001', 'pack');
  perform public.mint_instance('10000000-0000-0000-0000-000000000013', '30000000-0000-0000-0000-000000000001', 'shop');

  delete from public.purchases where buyer_id = '30000000-0000-0000-0000-000000000001';
  delete from public.balance_transactions where user_id = '30000000-0000-0000-0000-000000000001';

  -- ---------- promo codes ----------

  insert into public.promo_codes (code, bonus_type, bonus_value, max_uses, per_user_limit, is_active, starts_at, ends_at) values
    ('NUFFY100', 'fixed', 100, 500, 1, true, now() - interval '1 day', now() + interval '90 days'),
    ('NUFFY10', 'percent', 10, 500, 1, true, now() - interval '1 day', now() + interval '90 days')
  on conflict (code) do nothing;

  insert into public.seed_state (key) values ('demo_seed');
end $$;

-- ---------- проверка установки ----------

select
  (select count(*) from public.rarities)         as rarities,
  (select count(*) from public.levels)           as levels,
  (select count(*) from public.collections)      as collections,
  (select count(*) from public.chips)            as chips,
  (select count(*) from public.pack_versions)    as pack_versions,
  (select count(*) from public.promo_codes)      as promo_codes,
  (select count(*) from public.profiles_public)  as profiles_public,
  (select count(*) from public.seed_state)       as seed_applied;